export const API_URL = 'https://newsapi.org/v2/';

export const JWT_ALGORITHM = 'HS256'
export const TOTP_ALGORITHM = 'SHA1'
export const ERROR_STATUS = {
  DATABASE_ERROR: 500,
  VALIDATION_ERROR: 400,
  AUTHENTICATION_ERROR: 401,
  AUTHORIZATION_ERROR: 403,
  NOT_FOUND_ERROR: 404,
  INTERNAL_ERROR: 500,
  EXTERNAL_SERVICE_ERROR: 500,
  INVALID_TOKEN_ERROR: 401,
  HASH_ERROR: 500,
  FORBIDDEN_ERROR: 403,
  CONFLICT_ERROR: 409,
  BAD_REQUEST: 400,
  ERROR_CODE: 500,
  PERMISSION_ERROR: 403,
  NOT_AVALIDABLE_ERROR: 503,
  NOT_IMPLEMENTED_ERROR: 501,
  NOT_ACCEPTABLE_ERROR: 406,
  NOT_ALLOWED_ERROR: 405,
  NOT_SUPPORTED_ERROR: 405,
  LIMIT_EXCEEDED: 429,
  TWO_FACTOR_ERROR: 400,
}
